import { test, expect } from '@playwright/test';

// Drives the ConsumablesPlanner island by keyboard alone, against the static
// fixture served by tests/tools/fixtures/serve.mjs (see
// .factory/decisions/session-4.md — session 8 mounts the real component).
test.describe('ConsumablesPlanner — keyboard operation', () => {
  test('renders a correct default state before any interaction', async ({ page }) => {
    await page.goto('/consumables-planner.html');
    await expect(page.locator('#row-value-total')).toHaveText('480,000');
    await expect(page.locator('#row-value-trays')).toHaveText('3,750');
    await expect(page.locator('#quotation-link')).toHaveAttribute('href', /pt_grafts=120000/);
  });

  test('Tab reaches grafts-per-cycle, typing a new value re-renders every row', async ({
    page,
  }) => {
    await page.goto('/consumables-planner.html');

    await page.keyboard.press('Tab');
    await expect(page.locator('#grafts-per-cycle')).toBeFocused();
    await page.keyboard.press('ControlOrMeta+A');
    await page.keyboard.type('100000');
    await expect(page.locator('#row-value-total')).toHaveText('400,000');
    await expect(page.locator('#quotation-link')).toHaveAttribute('href', /pt_total=400000/);
  });

  test('Tab reaches the checked tray option, arrow keys switch tray and re-render', async ({
    page,
  }) => {
    await page.goto('/consumables-planner.html');

    await page.keyboard.press('Tab'); // grafts-per-cycle
    await page.keyboard.press('Tab'); // cycles-per-year
    await page.keyboard.press('Tab'); // the checked tray radio (128 cell)
    await expect(page.locator('#tray-128')).toBeFocused();

    await page.keyboard.press('ArrowRight');
    await expect(page.locator('#tray-200')).toBeFocused();
    await expect(page.locator('#row-working-trays')).toContainText('200 cell');
    await expect(page.locator('#row-value-trays')).toHaveText('2,400');

    // The focused option carries a visible focus indicator (not suppressed).
    const outline = await page
      .locator('label[for="tray-200"]')
      .evaluate((el) => getComputedStyle(el).outlineStyle);
    expect(outline).not.toBe('none');
  });

  test('renders a full row list rather than an empty shell', async ({ page }) => {
    await page.goto('/consumables-planner.html');
    // The assumptions text itself is static SSR copy generated by
    // assumptionLines() (see planner.test.ts) and owned by
    // ConsumablesPlanner.astro directly; this just confirms the rows render.
    await expect(page.locator('#planner-rows')).toBeVisible();
    await expect(page.locator('.row')).toHaveCount(8);
  });
});
